export const Strings = {
  app_name: 'nftlayers',
  dashboard_page: 'Dashboard',
  landing_page: 'About',
  go_to_app: 'Go to the app',
  add_layer: 'Add layer',
  new_layer: (i: string | number) => `Layer ${i}`,
  preview: 'Preview',
  values_used: 'Values used:',
  download: 'Download',
  drop_zone_prompt: 'Drag and drop some files here, or click to select files.',
  drop_zone_prompt_dragging: 'Drop the files here...',
  edit: 'Edit',
  save: 'Save',
  cancel: 'Cancel',
  confirm: 'Yes',
  close: 'Close',
  delete_layer: 'Delete',
  delete_layer_modal_title: (name: string) => `Delete the layer "${name}"?`,
  output_count: 'Images to generate:',
  allow_duplicates: 'Allow duplicates',
  use_bright_bg: 'Bright background',
  zipping: 'Compressing...',
  help: 'Help',
};
